# Base image
FROM python:3.9-slim-buster

# Making sure the output gets sent to terminal
ENV PYTHONUNBUFFERED=1

# Node
RUN apt -y update
RUN apt -y upgrade
RUN apt -y install curl
RUN curl -sL https://deb.nodesource.com/setup_16.x | bash
RUN apt-get install nodejs
RUN node -v
RUN npm -v

# Set Working Directory
WORKDIR /frontend

# Add `/frontend/node_modules/.bin` to $PATH
ENV PATH /frontend/node_modules/.bin:$PATH

# Copy everything
COPY ./frontend .

# Build application
RUN npm i -g yarn
RUN npm i dotenv-cli --save-dev
RUN yarn install
RUN yarn build:dev

# Set Working Directory
WORKDIR /backend

# Copy everything
COPY ./backend .
RUN cp .env.development .env

# Install dependencies
RUN pip3 --no-cache-dir install -r requirements.txt

# Copy to Backend Static Files
RUN cp -a /frontend/build/. /backend/build

# Expose port
EXPOSE 8000

# Launch application
CMD [ "gunicorn", "sample.wsgi", "-c", "gunicorn.conf.py" ]